openapi: "3.0.0"
info:
  version: 1.0.0
  title: Common Error entity

# Spec only contains models
paths: {}

components:
  schemas:
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
